local AyatData = {
    {
        awal = "Al-Fatihah ayat 1",
        teks = "Bismillahir rahmanir rahim",
        sambungan = "Alhamdu lillahi rabbil 'alamin"
    },
    {
        awal = "Al-Ikhlas ayat 1",
        teks = "Qul huwallahu ahad",
        sambungan = "Allahus samad"
    },
    {
        awal = "Al-Falaq ayat 1",
        teks = "Qul a'udzu birabbil falaq",
        sambungan = "Min syarri ma khalaq"
    },
    {
        awal = "An-Nas ayat 1",
        teks = "Qul a'udzu birabbin nas",
        sambungan = "Malikin nas"
    },
    {
        awal = "Al-Kautsar ayat 1",
        teks = "Inna a'tainakal kautsar",
        sambungan = "Fasalli lirabbika wanhar"
    }
}

return AyatData